### ISSUE TITLE
Ornaments should use `ornm` feature, not `swsh`

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/allura#11]
This font contains a number of ornamental glyphs such as border elements. These are currently accessed via the `swsh` feature. However, this feature is intended for swashed forms of the original glyph; in other words, when the `swsh` feature is applied, the original text should still be readable. Selecting ornament glyphs should be done through the `ornm` feature.

**Comment by vv-monsalve** [comment]
Thanks, @simoncozens. I'll inspect it. 

We've set up a range of development for all the TypeSetIt projects as there are many issues to solve, and improving OT Features is listed in L3. However, this is handy information, and please feel free to report everything you may find. All reports on this subject will be more than welcome.

**Comment by vv-monsalve** [comment]
Solved in the quick `v1.101` update.
