### ISSUE TITLE
Ș went missing in recent upgrade?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/allura#12]
A user wrote in,

> This character no longer exists, although recently it was represented correctly: `Ș`

**Comment by ambrozieputna** [comment]
There is definitely something wrong with the Ș/ș character.
More details here #3

**Comment by vv-monsalve** [comment]
I've done an update with a fix for this. Typically, after the PR the update could be online in one or two weeks.

**Comment by ambrozieputna** [comment]
What is the status of this? There is almost a month from the update you
published.
How can we check its progress?

**Comment by vv-monsalve** [comment]
Reported as [solved](https://github.com/googlefonts/allura/issues/3#issuecomment-964417611)
