### ISSUE TITLE
Font Mastering

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/allura#3]
**Diacritics**
- [x] Composite glyphs need to be made out of components using anchors
- [x] Comb.case are missing
- [x] Misaligned diacritics

**Glyphs & Outlines**
- [x] Some extreme points are missing
- [x] Review caron.alt spacing and kerning
- [ ] Inspect the [Outline Quality Checklist](https://github.com/googlefonts/allura/issues/2) and ensure everything is working well in Allura

**OT Features**
- [ ] Review inclusion of standard ligatures, e.g. fi is missing
- [ ] 'fina' feature should be used for stylistic alternates 03.

Stylistic Set 3
![Allura-s03](https://user-images.githubusercontent.com/48698976/109349346-ccdb5400-7843-11eb-8b54-2b800d34e208.png)

![Screen Shot 2021-02-26 at 15 02 41](https://user-images.githubusercontent.com/48698976/109349405-e4b2d800-7843-11eb-9f8e-4e9aae181f48.png)

**Comment by crystaltype** [comment]
@vv-monsalve I saw quite a lot of duplicate glyphs with .001 or .002 in the source file, should I delete these duplicate glyphs?
<img width="526" alt="Screen Shot 2021-05-31 at 08 40 40" src="https://user-images.githubusercontent.com/20129845/120128301-e649be80-c1eb-11eb-9e49-26856dcf8df6.png">

<img width="577" alt="Screen Shot 2021-05-31 at 08 41 31" src="https://user-images.githubusercontent.com/20129845/120128369-06797d80-c1ec-11eb-9524-15962a52009a.png">

**Comment by vv-monsalve** [comment]
Please inspect all the cases to be certain that they are the same glyph, once you confirm that yes, please delete the repeated ones.

**Comment by vv-monsalve** [comment]
Hi @crystaltype after merging the last PR there are still some repeated glyphs

![Screen Shot 2021-06-01 at 20 40 56](https://user-images.githubusercontent.com/48698976/120411052-c1536980-c319-11eb-8350-0b524099a7b9.png)

**Comment by ambrozieputna** [comment]
Hi @vv-monsalve .
Something broke when you solved the misaligned diacritics.
The ș is missing or broken.

Both in Chrome and Firefox, the ș is displayed like this:
![Screenshot 2021-09-16 011452](https://user-images.githubusercontent.com/29288655/133517231-40be1378-7f9d-4eb3-a9bc-4d53a5df04aa.jpg)

Link to the site where I use the font:
https://www.fundatiamaicabenedicta.ro/colectia-zoe-dumitrescu-busulenga-eminescu-viata-p5.html

On the Google Fonts site, in Chrome, the simulations is ok, but not in Firefox.
![Screenshot 2021-09-16 011813](https://user-images.githubusercontent.com/29288655/133517318-4cf9f379-ef52-446b-a826-5e55cebf533f.jpg)

Please solve this issue.
Thanks.

**Comment by vv-monsalve** [comment]
Hi @ambrozieputna, Thanks for reporting this. 
I'll inspect the font to see what the situation could be.

**Comment by ambrozieputna** [comment]
Hi @vv-monsalve 
You said you published an update, but the problem is still present on my site (see the attached picture).
Is the change not live yet?

![Screenshot 2021-11-01 123404](https://user-images.githubusercontent.com/29288655/139658718-04a96df6-41c9-422f-9207-67698524aebc.jpg)

**Comment by vv-monsalve** [comment]
> Is the change not live yet?

I've just confirmed and it is not online yet. We have had a hold on the publishing due to upper server engineer workflow priorities.

**Comment by ambrozieputna** [comment]
Thank you. It appears to be live now and the problem solved.
