### ISSUE TITLE
Horizontal regression

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/allura#9]
Hi @crystaltype 
There are some cases of spacing and kerning (particularly among uppercase letters, e.g. `T` `U` that are causing a horizontal regression.
Also, the main numbers version need to get back to the lining figures, and the current ones should be renamed with the `.osf` sufix, and create the OT feature for them.

### Text
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/120424903-e1435700-c332-11eb-8419-a843e75207d2.gif)

**Comment by crystaltype** [comment]
Hello @vv-monsalve, as we've discussed, the TU kerning pairs in the "After" version is better.
I discovered most of the T+UPPERCASE LETTER pairs have spacing issue.
Do we try to resolve it in the Level 1 improvement or leave it to level 2?

<img width="613" alt="Screen Shot 2021-06-03 at 18 00 14" src="https://user-images.githubusercontent.com/20129845/120634535-91c96c00-c495-11eb-983a-358c5a2f461c.png">

Suggestion:

<img width="536" alt="Screen Shot 2021-06-03 at 17 56 29" src="https://user-images.githubusercontent.com/20129845/120634768-d7863480-c495-11eb-8e2a-e0ff4a91bac9.png">


I think we can also change the right side bearing for T?
